//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetworkConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NetworkConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select station first..
        /// </summary>
        internal static string tx_AddInterfaceAndStation_pleaseselectstationfirst {
            get {
                return ResourceManager.GetString("tx_AddInterfaceAndStation_pleaseselectstationfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration seems to be broken please close the configurator now, and reopen the configuration..
        /// </summary>
        internal static string tx_configDataBaseEnforceConstraints_false {
            get {
                return ResourceManager.GetString("tx_configDataBaseEnforceConstraints_false", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while creating new object.
        /// </summary>
        internal static string tx_configtreeview_error_messagebox_title {
            get {
                return ResourceManager.GetString("tx_configtreeview_error_messagebox_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with getting information about address space.
        ///Please check your settings and DataProvider.
        ///This problem ca occurs when DataProvider is changed and new DataProvider 
        ///does not support this address space.
        ///One of the solution for this issue is to change the Block DataType now.
        ///The Default settings are used now.
        ///This message may occurs many until you resolv this issue..
        /// </summary>
        internal static string Tx_DataBlocksRowWrapper_AddressSpaceDescriptor {
            get {
                return ResourceManager.GetString("Tx_DataBlocksRowWrapper_AddressSpaceDescriptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program will run in demo version..
        /// </summary>
        internal static string Tx_DemoModeInfo {
            get {
                return ResourceManager.GetString("Tx_DemoModeInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are working in demo version - save comand  is not allowed..
        /// </summary>
        internal static string tx_DemoWriteErr {
            get {
                return ResourceManager.GetString("tx_DemoWriteErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IO Error.
        /// </summary>
        internal static string tx_IOErrCap {
            get {
                return ResourceManager.GetString("tx_IOErrCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License failure.
        /// </summary>
        internal static string tx_licenseCap {
            get {
                return ResourceManager.GetString("tx_licenseCap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A suitable license file couldn&apos;t be found..
        /// </summary>
        internal static string tx_LicenseErr {
            get {
                return ResourceManager.GetString("tx_LicenseErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to validate the license..
        /// </summary>
        internal static string tx_LicenseErrDef {
            get {
                return ResourceManager.GetString("tx_LicenseErrDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I cannot save the file to this location because:.
        /// </summary>
        internal static string tx_SaveErr {
            get {
                return ResourceManager.GetString("tx_SaveErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current settings of access rights are wrong ({0}) and will be change to default..
        /// </summary>
        internal static string tx_TagRowWrapper_AccessRights {
            get {
                return ResourceManager.GetString("tx_TagRowWrapper_AccessRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current settings of state trigger are wrong ({0}) and will be change to default..
        /// </summary>
        internal static string tx_TagRowWrapper_StateTrigger {
            get {
                return ResourceManager.GetString("tx_TagRowWrapper_StateTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag cannot be added. Please finish creating the block first..
        /// </summary>
        internal static string tx_TagsCollection_pleasecreatedatablockfirst {
            get {
                return ResourceManager.GetString("tx_TagsCollection_pleasecreatedatablockfirst", resourceCulture);
            }
        }
    }
}
